name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Considera actualizar a @v4 para últimas características y seguridad.

      - name: Install Node.js 22.x
        uses: actions/setup-node@v2 # Considera actualizar a @v4.
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2 # Considera actualizar a @v4.
      
      - name: Install Node.js 22.x
        uses: actions/setup-node@v2 # Considera actualizar a @v4.
        with:
          node-version: 22.x

      - name: Install vercel CLI
        run: npm install -g vercel # Asegúrate de que esta sea la versión más reciente si tienes problemas.

      - name: pull Vercel Environment Variables # <--- ¡Aquí está el cambio clave!
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
        env: # <--- Añade este bloque 'env' aquí
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN }}
       